# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@7ca6abe6b3b0e8b5421b88be48feee39cbf52c6a
        with:
          swift-version: ${{ matrix.swift }}
      - name: Get swift version
        run: swift --version
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test
