name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Swift 5.10 works with macos-14
          - os: macos-14
            swift: "5.10"
          # Swift 6.0 works with latest
          - os: macos-latest
            swift: "6.0"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test